//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvokeServices.PostXMLServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PostDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostXMLServiceReference.PostXmlServiceSoap")]
    public interface PostXmlServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki GetPostsResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosts", ReplyAction="*")]
        InvokeServices.PostXMLServiceReference.GetPostsResponse GetPosts(InvokeServices.PostXMLServiceReference.GetPostsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosts", ReplyAction="*")]
        System.Threading.Tasks.Task<InvokeServices.PostXMLServiceReference.GetPostsResponse> GetPostsAsync(InvokeServices.PostXMLServiceReference.GetPostsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosts", Namespace="http://tempuri.org/", Order=0)]
        public InvokeServices.PostXMLServiceReference.GetPostsRequestBody Body;
        
        public GetPostsRequest() {
        }
        
        public GetPostsRequest(InvokeServices.PostXMLServiceReference.GetPostsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPostsRequestBody {
        
        public GetPostsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostsResponse", Namespace="http://tempuri.org/", Order=0)]
        public InvokeServices.PostXMLServiceReference.GetPostsResponseBody Body;
        
        public GetPostsResponse() {
        }
        
        public GetPostsResponse(InvokeServices.PostXMLServiceReference.GetPostsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPostsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InvokeServices.PostXMLServiceReference.PostDto[] GetPostsResult;
        
        public GetPostsResponseBody() {
        }
        
        public GetPostsResponseBody(InvokeServices.PostXMLServiceReference.PostDto[] GetPostsResult) {
            this.GetPostsResult = GetPostsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostXmlServiceSoapChannel : InvokeServices.PostXMLServiceReference.PostXmlServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostXmlServiceSoapClient : System.ServiceModel.ClientBase<InvokeServices.PostXMLServiceReference.PostXmlServiceSoap>, InvokeServices.PostXMLServiceReference.PostXmlServiceSoap {
        
        public PostXmlServiceSoapClient() {
        }
        
        public PostXmlServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostXmlServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostXmlServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostXmlServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvokeServices.PostXMLServiceReference.GetPostsResponse InvokeServices.PostXMLServiceReference.PostXmlServiceSoap.GetPosts(InvokeServices.PostXMLServiceReference.GetPostsRequest request) {
            return base.Channel.GetPosts(request);
        }
        
        public InvokeServices.PostXMLServiceReference.PostDto[] GetPosts() {
            InvokeServices.PostXMLServiceReference.GetPostsRequest inValue = new InvokeServices.PostXMLServiceReference.GetPostsRequest();
            inValue.Body = new InvokeServices.PostXMLServiceReference.GetPostsRequestBody();
            InvokeServices.PostXMLServiceReference.GetPostsResponse retVal = ((InvokeServices.PostXMLServiceReference.PostXmlServiceSoap)(this)).GetPosts(inValue);
            return retVal.Body.GetPostsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InvokeServices.PostXMLServiceReference.GetPostsResponse> InvokeServices.PostXMLServiceReference.PostXmlServiceSoap.GetPostsAsync(InvokeServices.PostXMLServiceReference.GetPostsRequest request) {
            return base.Channel.GetPostsAsync(request);
        }
        
        public System.Threading.Tasks.Task<InvokeServices.PostXMLServiceReference.GetPostsResponse> GetPostsAsync() {
            InvokeServices.PostXMLServiceReference.GetPostsRequest inValue = new InvokeServices.PostXMLServiceReference.GetPostsRequest();
            inValue.Body = new InvokeServices.PostXMLServiceReference.GetPostsRequestBody();
            return ((InvokeServices.PostXMLServiceReference.PostXmlServiceSoap)(this)).GetPostsAsync(inValue);
        }
    }
}
